replicaCount: 1

global:
  imageRegistry: ""
  imagePullSecrets: []
  multiTenancyEnabled: false

image:
  registry: docker.io
  repository: levoai/detection
  pullPolicy: IfNotPresent
  pullSecrets: []
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  # fsGroup: 2000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

env:
  LEVOAI_ORG_ID: ""
  LEVOAI_BASE_URL: ""
  RABBITMQ_HOST: "levoai-rabbitmq:5672"
