apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "protection.name" . }}-modsec
data:
  custom-rules.conf: |
    SecRule REQUEST_HEADERS:User-Agent "@contains BadBot" \
        "id:1001,phase:1,deny,log,msg:'Bad UA detected'"
  
