apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "protection.name" . }}-runtime
{{- $runtimeEnv := .Values.runtimeEnv | default dict }}
data:
  {{- if $runtimeEnv }}
  {{- range $key, $value := $runtimeEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- else }}
  {}
  {{- end }}
