{{- if .Values.confD.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "protection.name" . }}-confd
data:
{{- range $name, $content := .Values.confD.files }}
  {{ $name }}: |
{{ $content | nindent 4 }}
{{- end }}
{{- end }}
