apiVersion: v1
kind: Service
metadata:
  name: {{ include "protection.name" . }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "protection.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.portHttp }}
      targetPort: http
    {{- if .Values.tls.enabled }}
    - name: https
      port: {{ .Values.service.portHttps }}
      targetPort: https
    {{- end }}
    - name: admin
      port: {{ .Values.service.portAdmin }}
      targetPort: admin
